name = "Yolo-1.12.2"
author = "ahdg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93a90e1ce7199e9bf2f5ab302414a12486c47be9c36aac0cd8dc108fd5e1e7c0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
